repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.4
  hooks:
    # Run the linter
    - id: ruff
      args: [ --fix ]
    # Run the formatter
    - id: ruff-format
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-added-large-files
      args: ['--maxkb=2000'] 
- repo: local
  hooks:
    - id: time-restriction
      name: Time-restricted commits
      entry: .githooks/restrict-commit-hours.sh
      language: script
      pass_filenames: false
      always_run: true
      stages: [pre-commit]