name: electronsandstuff
channels:
  - conda-forge
dependencies:
  - jupyter
  - matplotlib
  - numpy
  - openpmd-beamphysics
  - pandas
  - pip
  - pre-commit
  - pydantic
  - pytest
  - python=3.11
  - scipy
  - xopt
  - pip:
    - paretobench
    - KDEpy
